# Generated by Django 4.1 on 2022-10-09 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='divide',
        ),
        migrations.DeleteModel(
            name='multiply',
        ),
        migrations.DeleteModel(
            name='subtract',
        ),
    ]
