# Generated by Django 4.1 on 2022-10-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_delete_divide_delete_multiply_delete_subtract'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num1', models.FloatField()),
                ('num2', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='add',
        ),
    ]
