# Generated by Django 4.1 on 2022-10-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_calculator_delete_add'),
    ]

    operations = [
        migrations.CreateModel(
            name='Divide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num1', models.FloatField()),
                ('num2', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Multiply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num1', models.FloatField()),
                ('num2', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Subtract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num1', models.FloatField()),
                ('num2', models.FloatField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Calculator',
            new_name='Add',
        ),
    ]
